CREATE TABLE INTERN (
    ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FNAME VARCHAR(10) NOT NULL, 
    MNAME VARCHAR(10),
    LNAME VARCHAR(10) NOT NULL,
    ADDRESS VARCHAR(100),
    SEX CHAR NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PHONE VARCHAR (11) NOT NULL,
    UNIVERSITY VARCHAR(10) NOT NULL,
    DEPARTMENT VARCHAR(10) NOT NULL,
    STUDY_YEAR VARCHAR(10) NOT NULL
);

CREATE TABLE INSTRUCTOR (
    INS_ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FNAME VARCHAR(10) NOT NULL, 
    MNAME VARCHAR(10),
    LNAME VARCHAR(10) NOT NULL,
    SEX CHAR NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PHONE VARCHAR INT(11) NOT NULL
);

CREATE TABLE COURSE_GROUP (
    GNO INT(5) NOT NULL,
    COURSE_NAME VARCHAR(20) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    FIRST_INS_ID INT(10) NOT NULL,
    SECOND_INS_ID INT(10),
    THIRD_INS_ID INT(10),
    PRIMARY KEY (GNO,COURSE_NAME)
);

CREATE TABLE ENROLL (
    INTERN_ID INT(10) NOT NULL,
    GNO INT(5)NOT NULL,
    COURSE_NAME VARCHAR(20) NOT NULL,
    PAYMENT BOOLEAN NOT NULL,
    PRIMARY KEY(INTERN_ID,GNO,COURSE_NAME)
);

CREATE TABLE COURSE (
    NAME VARCHAR(20) NOT NULL PRIMARY KEY,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE ROBOT_GRADE (
    INTERN_ID INT(10) NOT NULL PRIMARY KEY,
    GNO INT(5) NOT NULL,
    GRADE_PERCENTAGE DECIMAL(5,2) NOT NULL,
    GRADE_CLASS CHAR NOT NULL
);

CREATE TABLE THREE_D_GRADE (
    INTERN_ID INT(10) NOT NULL PRIMARY KEY,
    GNO INT(5) NOT NULL,
    GRADE_PERCENTAGE DECIMAL(5,2) NOT NULL,
    GRADE_CLASS CHAR NOT NULL
);

CREATE TABLE CNC_GRADE (
    INTERN_ID INT(10) NOT NULL PRIMARY KEY,
    GNO INT(5) NOT NULL,
    MILLING_GP DECIMAL(5,2) NOT NULL,
    TURNING_GP DECIMAL(5,2) NOT NULL,
    PUNCHING_GP DECIMAL(5,2) NOT NULL,
    MILLING_CLASS CHAR NOT NULL,
    TURNING_CLASS CHAR NOT NULL,
    PUNCHING_CLASS CHAR NOT NULL
);


